# Generated by Django 3.2 on 2021-06-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'StudentInfo',
                'verbose_name_plural': 'StudentInfo',
            },
        ),
        migrations.DeleteModel(
            name='ClientInfo',
        ),
    ]
